### ISSUE TITLE
🐛 bs-google-map, google-map does not respect [ng-style]

### ISSUE THREAD

**Issue by RobertVogt** [BeSpunky/angular-google-maps#3]
**Describe the bug**
Setting the absolute size of a map and allowing for dynamic sizing is key in many scenarios however bs-google-map and google-map ignore ng-style and default's to width 100% height:100% with now to override this.

**To Reproduce**
Try adding a specific height in ng-style, scss and watch the map load at 100%

**Expected behavior**
Expected behavior would be that when [ngStyle] gets parameter updated then it would dynamically reflect in bs-google-map

**Screenshots**
![image](https://user-images.githubusercontent.com/5022736/144916546-639bbf76-006e-4827-a2fe-a5d8e3a10421.png)
![image](https://user-images.githubusercontent.com/5022736/144916760-dbef4771-9441-455a-9d44-45af604e78d3.png)
![image](https://user-images.githubusercontent.com/5022736/144916956-53d01b52-b647-4f67-8d4b-318554fa46d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 96.0.4664.45

**Smartphone (please complete the following information):**
 N/A

**Additional context**

**Comment by RobertVogt** [comment]
I was able to work around this by grabbing the "google-map" class from the DOM and altering it.

**Comment by BeSpunky** [comment]
> I was able to work around this by grabbing the "google-map" class from the DOM and altering it.

Well done. Glad to hear you've figured it out. 👍

For future references, `ngStyle` will not work as it affects the component element itself, but not the map. To affect the map you need to modify the internal `div` on which Google Maps has rendered the map.

The library sets the map's height to 100% and adds the `.google-map` css class to the `div` so the developer can access it and provide further styling.

[More about styling](https://bs-angular-g-maps.web.app/docs/additional-documentation/the-map.html#styles)
[Live example](https://stackblitz.com/edit/bs-google-maps-map-options?file=src/app/map/map.component.css)
